### ISSUE TITLE
Feature request: make log level configurable

### ISSUE THREAD

**Issue by paulrutter** [myndzi/wtfnode#26]
I might create a PR myself, but for the time being this issue asks for the following:

- make the log level configurable (console.log, console.info, console.warn, console.error)

This is needed because some logging tools ignore console.log (which is "debug" level) by default, making the logging useless.
@myndzi What do you think of making this configurable?

**Comment by myndzi** [comment]
I'm kind of curious what logging tools manipulate console.log etc. directly in a way that would affect this module in normal use; it should have a stdout/stderr reference early, but I guess if you monkey patch console it would be affected.

The trick here is that I can't easily use the patterns I normally would want to in order to provide configuration options; wtfnode has to load early so it can monkey patch core Node stuff. 

How are you using this? I'm guessing you're using it as a module and using `wtf.dump()`? What if I provided a return value with the full text (or possibly just the data)? Or let you pass a stream for it to write to? (e.g. process.stderr)

**Comment by paulrutter** [comment]
Hi @myndzi,

Indeed, i'm using a module (https://github.com/nanlabs/econsole) that intercepts console.x.
By configuration, some log levels are not send to stderr/stdout, which leads to my issue.

Correct, i'm using wtf.dump(). A stream to write to would be helpful, so i can redirect the output to the desired console.x function.

**Comment by myndzi** [comment]
OK. You should use something else, that's a bad way to go. But it's an easy enough thing to account for; what I'll do is allow you to pass wtf.dump() a `log` argument, and call that function if supplied in order to log messages. They'll just be the strings I'm writing to the console.

**Comment by myndzi** [comment]
@paulrutter try `wtfnode@beta`. See the git master readme for docs on using `wtf.setLogger`. Let me know if it solves your problem?

**Comment by paulrutter** [comment]
Thanks, will check it out coming week.

**Comment by paulrutter** [comment]
Econsole is working pretty good for us; it easily allows us to suppress certain loglevels. 

Your fix works like a charm; i would suggest to merge this to master 👍 
Thanks!

**Comment by myndzi** [comment]
Published.

On logging: log level selection is pretty basic, and is a part of pretty much every logging package -- you don't need to monkey patch core functionality to do it, and doing so is just asking for headaches (like this one). Depending on what you're after, I'd point you towards either [Bunyan](https://www.npmjs.com/package/bunyan) for robust logging or [Debug](https://www.npmjs.com/package/debug) for configurable/filterable debug logging. It's your time and energy, though :)

**Comment by paulrutter** [comment]
Thanks :)
I will take a look at other modules, it indeed doesn't seem necessary to do so.
