### ISSUE TITLE
Socket fd -1

### ISSUE THREAD

**Issue by pgraham** [myndzi/wtfnode#30]
I've started seeing some weird output from wtfnode and my process has not been terminating:

```
- File descriptors: (note: stdio always exists)
  - fd 1 (tty) (stdio)
  - fd 2 (tty) (stdio)
- Sockets:
  - fd -1
```

This isn't really an issue with wtfnode but am wondering if you have any clues as to what socket `fd -1` is and where I would start looking for the source.?

**Comment by myndzi** [comment]
If you can give me a node version and some repro code, I can look into it?

Items listed here are `instanceof Socket`. Socket isn't always a network socket (see comment: https://github.com/myndzi/wtfnode/blob/master/index.js#L374), and this message is printed when I wasn't able to locate a network address: https://github.com/myndzi/wtfnode/blob/master/index.js#L457

I wouldn't be surprised if, for example, something under the hood changed in new Node versions and this checking is behaving differently now. I expect that fd -1 probably means a file descriptor doesn't exist or used to exist and now doesn't, something like that. There's a chance that the socket has been cleaned up but wasn't removed from `process._getActiveHandles`, and maybe won't exist if you wait for a little while?

However, since that's the only non-stdio thing in the list, it would seem to be the culprit. Closer inspection in a debugger, or just logging the details of `process._getActiveHandles()` may reveal what it actually is, and if it's a thing I haven't instrumented then I can likely instrument it and thus grab the source info for what created it.

**Comment by myndzi** [comment]
Closing because no response
