### ISSUE TITLE
error when using cluster

### ISSUE THREAD

**Issue by undefined-moe** [myndzi/wtfnode#38]
node v14
when using wtfnode with cluster, throws an EPIPE error

```
Error: write EPIPE
    at process.target._send (internal/child_process.js:835:20)
    at process.target.send (internal/child_process.js:706:19)
    at sendHelper (internal/cluster/utils.js:26:15)
    at send (internal/cluster/child.js:193:10)
    at EventEmitter.cluster._setupWorker (internal/cluster/child.js:46:3)
    at initializeClusterIPC (internal/bootstrap/pre_execution.js:342:13)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:65:3)
    at internal/main/run_main_module.js:7:1
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:314:20)
    at internal/child_process.js:839:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by myndzi** [comment]
Hi there!

`write EPIPE` is an error indicating that the other end of a pipe is no longer present. You would get this error when, for example, attempting to send a message to a child that has exited already. Since there are no lines of code in the stack trace anywhere in `wtfnode`'s source, it doesn't appear to be a _code_ error in wtfnode (e.g. newer version of node changing something and now wtfnode is doing an incompatible thing).

I have a minimal test already that exercises the `cluster` module's forking behavior, and I'm not encountering any problems on Node 14.9.0. This means that likely you're either using some functions that are affected but I've not exercised, or the problem doesn't actually have anything to do with wtfnode. 

If you're using the CLI interface (`wtfnode myapp.js`) and using ctrl+c to dump the output, `wtfnode` dumps the open handles and exits the process. It may be the case that this is causing a process you expect to be present to now have exited. This isn't really a bug in wtfnode so much as an unexpected eventuality that you may want to guard yourself against anyway. (The parent should probably not crash implicitly if a child crashes/exits, though it might want to print a useful message and exit)

If you're using the module interface (`var wtf = require('wtfnode')`), it's possible that some monkey patch no longer behaves nicely with Node.js, or that you're using the `cluster` module in a way I haven't tested/exercised.  My own basic test is not reproducing the problem, though, so I'm going to need your help. What _exact_ version of node are you having problems with? What precisely are the steps you're taking that cause the error? What makes you think that `wtfnode` is involved? (How does it differ from otherwise?) Are you able to create a minimal reproduction example?

**Comment by undefined-moe** [comment]
thanks for your reply.

i'm using node v14.8.0 and code is from https://github.com/hydro-dev/Hydro

wtfnode crashs the whole process, but the code works properly without it.

- clone the repo, run yarn
- modify packages/hydrooj/src/loader.ts:
- add `import wtfnode from 'wtfnode'`
- add `wtdnode.dump()` in function terminate at line 53
- run `yarn build`
- run `yarn start`

**Comment by myndzi** [comment]
First off, sorry it took me so long to get to this.

For your info, I had a number of problems with this process:
- Not familiar with yarn workspaces; tried adding wtfnode from packages/hydrooj and got a TS module resolution error using import. Changing to `require` worked. Not sure why import doesn't work but should make no real difference?
- Building then gave the error `Addon not found: @hydrooj/customize`, but it cannot be found in npm. I noticed the message saying `Please also install @hydrooj/ui-default`, which I did, but got the same error. Discovered that packages/customize is a submodule, initialized it. (Maybe should have been a build failure?)
- Then got errors with alipay-sdk; re-running `yarn` took care of it (since the `customize` directory was empty, the initial `yarn` run didn't have a `package.json` to tell it about the extra dependencies)

Now I get the error you had.

Not included in your report, but important, is this error:
```
[E] entry/master Cannot start setup process. TypeError: Cannot redefine property: __callSite
    at Function.defineProperties (<anonymous>)
    at EventEmitter.cluster.fork (/home/myndzi/wtfnode/index.js:372:20)
    at fork (/home/myndzi/Hydro/packages/hydrooj/dist/loader.js:89:30)
    at entry (/home/myndzi/Hydro/packages/hydrooj/dist/loader.js:94:29)
    at Object.load (/home/myndzi/Hydro/packages/hydrooj/dist/entry/master.js:67:15)
    at async entry (/home/myndzi/Hydro/packages/hydrooj/dist/loader.js:110:20)
    at async load (/home/myndzi/Hydro/packages/hydrooj/dist/loader.js:236:21)
error Command failed with exit code 1.
```

I can't seem to figure out how to reproduce the actual behavior, but the hook in `fork` forgot to check whether the callsite was already defined. I don't know why it's being called with an already-hooked object, but it's a clear error. I've published a fix to the `beta` branch; you can update with `yarn add wtfnode@0.8.4`. If you can verify the crash goes away, I'll update the main distribution.

Also seen is some weirdness around one of the Server classes in your code. I haven't yet been able to identify what's going on; it seems to be a Server object with no address info, might be related to fork. Something is adding a `fail` event handler (maybe Typescript or some library?) to it, but since it's not bound in your application code there's no callsite reference. This can be safely ignored, though I'd like to figure out what the Server object _is_ and give better information about it. That doesn't block fixing this, however.

**Comment by undefined-moe** [comment]
Thanks for your reply.
I didn't see `__callSite` error message as my database is already set.(maybe worker process startup error was caught without displaying.)
Maybe Server class is caused by cluster? all listen() called on worker will be handled by master process.
and 0.8.4 works for me.

**Comment by undefined-moe** [comment]
the import statement is handled by typescript compiler, while require() is handled by node, sometimes cache will cause resolution error, clean tsbuildinfo file and delete dist folder might help. and @types/wtfnode is suggested to install when using typescript.

**Comment by myndzi** [comment]
I never made a types file... this whole thing is a big hack ;) I had a partly-done rewrite that was much cleaner a while back but I haven't been working on it.

Thanks for confirming, I'll push 0.8.4 to latest
