### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by yakkomajuri** [myndzi/wtfnode#42]
Hey! Thanks a lot for this package. It's super helpful.

I have a need for checking open timers and sockets, but would not want them logged - I'd rather have them accessible in my code. There would be a workaround for this, but best would be if I could fork the repo and make the necessary tweaks (and would happily put up a PR upstream for it if desired). 

However, the repo has no license. Is there any intention of adding a license to this repo? 

Thanks again!

cc @myndzi

**Comment by yakkomajuri** [comment]
I see now that `package.json` seems to specify `ISC` - is that correct? Any chance to add in a license file to correspond?

**Comment by myndzi** [comment]
Happy to do that. I'm not particularly informed of the proper procedures for licenses in public repositories, but my intent here is definitely not to keep it to myself :)

A while back I was working on a new version of wtfnode with thorough tests and a more proper programmatic API, but my time and energy for hobby projects is extremely limited these days so it's only in a half-complete state. My goals with this project are to generally be dependency-free and backwards compatible (though it's debatable how far back is worthwhile for backwards-compatibility's sake -- but wtfnode has always worked on 0.10.0 and up, and I'd like to keep it that way).

I'm not sure what you have in mind, but I'm happy to accept a PR that meets these criteria (and, preferably, changes the least amount of code -- since apparently there are lots of users, I don't want to break them, either!)

**Comment by myndzi** [comment]
(done)

Not publishing a new version to NPM, since there's no code change and this repository should be considered the source of truth

**Comment by yakkomajuri** [comment]
Awesome, thank you so much!
